### ISSUE TITLE
Can we call a skill from another skill in opsdroid

### ISSUE THREAD

**Issue by satwika007** [opsdroid/opsdroid#1801] opened 2021-07-22 12:39 UTC
I want to have a functionality where in i can call one skill from another. Is it possible?

**Comment by Cadair** [comment] 2021-07-22 14:36
In theory yes, as long as it's importable. The issue is that skills loaded by the opsdroid automagical loader are not globally importable. I shall have to see what @jacobtomlinson has to say on the matter.

**Comment by jacobtomlinson** [comment] 2021-07-23 09:10
If you have multiple skills within one class then they can directly call each other.

```python
from opsdroid.matchers import match_regex
from opsdroid.skill import Skill


class FooSkill(Skill):
    @match_regex(r"foo")
    async def foo_method(self, event):
        await event.respond("fooooo")

    @match_regex(r"bar")
    async def bar_method(self, event):
        await self.foo_method(event)
```

If you are talking about across skills in the configuration you have a couple of different options.

Let's assume we have two skills `foo.py` and `bar.py` both stored in our home directory and configured with:

```yaml
...

skills:
  foo:
    path: ~/foo.py

  bar:
    path:  ~/bar.py
```

All loaded skill methods (anything with a `@match_foo` decorator) can be found within `opsdroid.skills`, although this is just a list of pointers so you would have to do some name inspection.

```python
# foo.py
from opsdroid.matchers import match_regex
from opsdroid.skill import Skill


class FooSkill(Skill):
    @match_regex(r"foo")
    async def foo_method(self, event):
        await event.respond("fooooo")
```

```python
# bar.py
from opsdroid.matchers import match_regex
from opsdroid.skill import Skill


class BarSkill(Skill):
    @match_regex(r"bar")
    async def bar_method(self, event):
        for skill in self.opsdroid.skills:
            if skill.__name__ == "foo_method":
                await skill(event)
```

Alternatively, you can import the skill yourself. For any skill that opsdroid installs via `path` or `repo` it gets smushed into a dynamic module at runtime called `opsdroid_modules` (or will be after bugfix #XXX). 

```python
# foo.py
from opsdroid.matchers import match_regex
from opsdroid.skill import Skill


class FooSkill(Skill):
    @match_regex(r"foo")
    async def foo_method(self, event):
        await event.respond("fooooo")
```

```python
# bar.py
from opsdroid.matchers import match_regex
from opsdroid.skill import Skill


class BarSkill(Skill):
    @match_regex(r"bar")
    async def bar_method(self, event):
        from opsdroid_modules.skill.foo import FooSkill
        # Do things with `FooSkill`, just remember this is the base class not the instance loaded into opsdroid
```

**Comment by jacobtomlinson** [comment] 2021-07-23 09:18
Perhaps we should add an `opsdroid.get_skill(name)` utility similar to `get_connector` and `get_database` which simplifies grabbing a skill by it's method name. 

We would also support other notations then like:
- `skill = self.opsdroid.get_skill("foo_method")`
- `skill = self.opsdroid.get_skill("FooSkill.foo_method")`
- `skill = self.opsdroid.get_skill("foo.FooSkill.foo_method")`
- `skill = self.opsdroid.get_skill("opsdroid_modules.skill.foo.FooSkill.foo_method")`

If there are multiple skills with colliding names it would just return the first one found, or error out. But we could support being very explicit to specifically grab the skill you want.

**Comment by satwika007** [comment] 2021-07-23 14:37
Yeah, it would be great if we can do that. Also "for skill in self.opsdroid.skills" works for my usecase. Thanks for your time !!!

**Comment by jacobtomlinson** [comment] 2021-07-23 16:33
I've raised #1803 to cover adding this new method. Closing this as you have a suitable workaround.

**Closed by jacobtomlinson** 2021-07-23 16:33 UTC
Labels: question, skill developent
