### ISSUE TITLE
We should probably not be pinning a version of setuptools

### ISSUE THREAD

**Issue by Cadair** [opsdroid/opsdroid#1395] opened 2020-03-12 09:38 UTC
I am not entirely sure why we are pinning an exact version of setuptools, but it seems like a bad idea to me. Many linux distributions ship a specific version of setuptools and people might not want to update it, also if you are in a development environment it's very easy to end up in a situation where opsdroid wont start because of the incorrect version being installed.

i.e.:
``` 
opsdroid start
Traceback (most recent call last):
  File "/home/stuart/.virtualenvs/opsdroid/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/home/stuart/.virtualenvs/opsdroid/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/stuart/.virtualenvs/opsdroid/lib/python3.8/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (setuptools 45.2.0 (/home/stuart/.virtualenvs/opsdroid/lib/python3.8/site-packages), Requirement.parse('setuptools==46.0.0'), {'opsdroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stuart/.virtualenvs/opsdroid/bin/opsdroid", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/stuart/.virtualenvs/opsdroid/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/home/stuart/.virtualenvs/opsdroid/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/home/stuart/.virtualenvs/opsdroid/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/stuart/.virtualenvs/opsdroid/lib/python3.8/site-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/stuart/.virtualenvs/opsdroid/lib/python3.8/site-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/stuart/.virtualenvs/opsdroid/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'setuptools==46.0.0' distribution was not found and is required by opsdroid
```

I propose we only pin a minimum version of setuptools which we actually require (likely ~40 iirc).

**Comment by FabioRosado** [comment] 2020-03-22 16:47
It took me a while to  reply but I agree with you might be better to choose a minimum version for setup tools and accept any new versions. Not sure why we are pinning the versions but might be a way to try and keep the dependencies updated maybe 🤔

**Comment by jacobtomlinson** [comment] 2020-04-07 11:51
I'm going to close this as a duplicate of #651. I agree we should relax our package pinning.

@Cadair had some good points about moving our deps into `setup.cfg`. If this something you could pick up?

**Closed by jacobtomlinson** 2020-04-07 11:51 UTC
Labels: discussion

**Comment by Cadair** [comment] 2020-04-07 12:32
potentially, I will keep it in mind :smile:
