### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by dgacias** [opsdroid/opsdroid#791] opened 2018-12-24 08:27 UTC
# Description
It just crashed with a memory error, a restart made it work again.

## Steps to Reproduce
Just running it on the weekend produced it, using opsdroid:dev docker

## Experienced Functionality
This is the log: https://pastebin.com/2nW6G0mt

## Versions
- **Opsdroid dev container**
- **Python version 3.6**
- **Amazon linux 2, docker version 18.06.1-ce**

## Configuration File
The configuration file just have the slack connector, everything else is default.
I have 2 custom skills but they just do curls to external api's, none of them were triggered on the weekend.

**Comment by FabioRosado** [comment] 2018-12-24 15:03
I have been trying to break my opsdroid to see if I could get that `NameError: '_' ...` exception, I know exactly what is it about (the gettext), but I had a feeling we had fixed this issue, having it in this log made me a bit confused so I been trying to get it but every thing I tried hasn't produced the error yet.

Looking at the logs it seems that the slacker couldn't connect to the server for some reason, it started by trying to reconnect and then you might have ran out of memory?

If that is the case perhaps this is something related with #743

**Comment by jacobtomlinson** [comment] 2018-12-30 07:38
This could potentially be related to #743, especially as it seems to be the slack connector which is causing the problem.

**Comment by FabioRosado** [comment] 2018-12-30 09:07
I read something about this memoryerror and slacker - some people on stackoverflow said that it could be the keep alive method. Might be something worth checking?

**Comment by jacobtomlinson** [comment] 2019-01-20 11:33
I'm going to close this as a duplicate of #743

**Closed by jacobtomlinson** 2019-01-20 11:33 UTC
Labels: bug
