### ISSUE TITLE
Error during installation of opsdroid

### ISSUE THREAD

**Issue by kaiiyer** [opsdroid/opsdroid#821] opened 2019-01-28 12:45 UTC
# Description
There was an error while installing opsdroid on Debian, Kali Linux and Parrot GNU.

## Steps to Reproduce
$ pip3 install opsdroid
$ opsdroid

## Expected Functionality
Proper installation of opsdroid on the machine.

## Experienced Functionality
Error while installing the packages for opsdroid v0.13.0

## Versions
- opsdroid v0.13.0
- Python 3.6.8
- Parrot 3.11 and Kali 2017

## Additional Details
<img src="https://66.media.tumblr.com/3ab4d29ba31edcb76d6706f33e33e9a6/tumblr_pm1k6hzCUi1wnca1uo1_1280.png" alt="screenshot">

**Comment by jacobtomlinson** [comment] 2019-01-28 13:08
Thanks for raising this. It looks like the shell connector has been updated ready for `0.14.0` but this has broken backward compatibility. This highlights the issues raised in #92.

You can wait for `0.14.0` which I'm hoping to get out today and that should resolve the issue. In the eman time you can also disable the shell connector in the config ( run `opsdroid -e` and comment out the shell connector line) and use [opsdroid desktop](https://github.com/opsdroid/opsdroid-desktop).

In the long term we should accelerate the work to extract the web ui from opsdroid desktop into a separate package and then include it in opsdroid core, see opsdroid/opsdroid-desktop#21.

**Comment by FabioRosado** [comment] 2019-02-14 15:51
@kaiiyer could you please update opsdroid and check if the issue is fixed? I am eager to close this issue 😄 👍

**Comment by kaiiyer** [comment] 2019-03-17 06:58
@FabioRosado Yeah it's fixed. You can close the issue :+1:

**Closed** 2019-03-17 13:55 UTC
Labels: bug
